client_config_backend: settings
client_config:
  client_id: 836875655828-kpgj2ofsqu56n3ogb9hq7mitecev8utq.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install